### ISSUE TITLE
question about the code

### ISSUE THREAD

**Issue by laizy** [zkcrypto/bls12_381#95]
Hi, I just started learning pairing crypto, and try to read the code, I am confused about the following code:
https://github.com/zkcrypto/bls12_381/blob/34dab74ae44cd77dfa867928dd2e6c8383d8dc9d/src/fp6.rs#L113-L119
why not using the following expression to calculate t1 ?:
```rust
      let t1 = self.c2 * c1; 
```

**Comment by str4d** [comment]
Indeed, in this particular method this is slightly faster, because you remove several unnecessary additions and subtractions, without increasing the number of multiplications. I suspect this was written like it is to more closely match the equations, but I don't think it is necessary to do that when there is a (small but) clear performance win.
